AWSTemplateFormatVersion: 2010-09-09

Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id

  EDLUsername:
    Type: String

  EDLPassword:
    Type: String
    NoEcho: true

  RtcGammaImage:
    Type: String

  AuthPublicKey:
    Type: String

  AuthAlgorithm:
    Type: String
    Default: RS256

  DomainName:
    Type: String

  CertificateArn:
    Type: String

Outputs:

  ApiUrl:
    Value: !GetAtt Api.Outputs.Url

Resources:

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StepFunctionArn: !GetAtt Cluster.Outputs.StepFunctionArn
        JobQueueArn: !GetAtt Cluster.Outputs.JobQueueArn
        RtcGammaJobDefinition: !GetAtt Cluster.Outputs.RtcGammaJobDefinition
        AuthPublicKey: !Ref AuthPublicKey
        AuthAlgorithm: !Ref AuthAlgorithm
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
      TemplateURL: api/cloudformation.yml

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcId: !Ref VpcId
        EDLUsername: !Ref EDLUsername
        EDLPassword: !Ref EDLPassword
        RtcGammaImage: !Ref RtcGammaImage
        ProductBucket: !Ref Bucket
      TemplateURL: batch-cluster/cloudformation.yml

  StepFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        JobQueueArn: !GetAtt Cluster.Outputs.JobQueueArn
        RtcGammaJobDefinition: !GetAtt Cluster.Outputs.RtcGammaJobDefinition
      TemplateURL: step-function/cloudformation.yml

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: False
        RestrictPublicBuckets: False

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${Bucket.Arn}/*"
