AWSTemplateFormatVersion: 2010-09-09

Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id

  EDLUsername:
    Type: String

  EDLPassword:
    Type: String
    NoEcho: true

  RtcGammaImage:
    Type: String

  AuthPublicKey:
    Type: String

  AuthAlgorithm:
    Type: String
    Default: RS256

  DomainName:
    Type: String

  CertificateArn:
    Type: String

Outputs:

  ApiUrl:
    Value: !GetAtt Api.Outputs.Url

Resources:

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StepFunctionArn: !GetAtt Cluster.Outputs.StepFunctionArn
        JobQueueArn: !GetAtt Cluster.Outputs.JobQueueArn
        RtcGammaJobDefinition: !GetAtt Cluster.Outputs.RtcGammaJobDefinition
        AuthPublicKey: !Ref AuthPublicKey
        AuthAlgorithm: !Ref AuthAlgorithm
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
      TemplateURL: api/cloudformation.yml

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcId: !Ref VpcId
        EDLUsername: !Ref EDLUsername
        EDLPassword: !Ref EDLPassword
        RtcGammaImage: !Ref RtcGammaImage
      TemplateURL: batch-cluster/cloudformation.yml
