AWSTemplateFormatVersion: 2010-09-09

Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id

  EDLUsername:
    Type: String

  EDLPassword:
    Type: String
    NoEcho: true

  RtcGammaImage:
    Type: String

  ProductLifetimeInDays:
    Type: Number
    MinValue: 1
    Default: 14

  AuthPublicKey:
    Type: String
    Default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBU3T16Db/88XQ2MTHgm9uFALjSJAMSejmVL+tO0ILzHw2OosKlVb38urmIGQ+xMPXTs1AQQYpJ/CdO7TaJ51pv4iz+zF0DYeUhPczsBEQYisLMZUwedPm9QLoKu8dkt4EzMiatQimBmzDvxxRkAIDehYh468phR6zPqIDizbgAjD4qgTd+oSA9mDPBZ/oG1sVc7TcoP93FbO9u1frzhjf0LS1H7YReVP4XsUTpCN0FsxDAMfLpOYZylChkFQeay7n9CIK8em4W4JL/T0PC218jXpF7W2p92rfAQztiWlFJc66tt45SXAVtD1rMEdWGlzze4acjMn4P7mugHHb17igtlF82H/wpdm84qTPShvBp/F4YZejgAzOAxzKVbCQ8lrApk1XYVDRAVk3AphfvNK5IC/X9zDSXstH9U94z8BTjkL2fR4eKzFu5kkvVoGHAACIv72QvH06Vwd0PNzLyaNXr9D5jO61EbR4RfpbzvAG0IzgXsUq0Rj7qwvzTCu6yLwTi/fn9bmRaOQNPtBch4ai5w7cfUWe2r7ZPv31AXPm1A+aGXvYTEZkiQMrBN/dXlNdUmafNNDoMBm/frQhMl+2DZp+C9GXCr2Z/JmYUHO8PaEj6UyYTkkrmtZNlZ43Nd2TblPEzL0pprJM9MxEf2Peaai8GKmTJz6C5tSGU+XdZQ== root@9dce6b43747e

  AuthAlgorithm:
    Type: String
    Default: RS256

  AuthGroupName:
    Type: String

  AuthAppUid:
    Type: String
    Default: asf_urs

  DomainName:
    Type: String

  CertificateArn:
    Type: String

Outputs:

  ApiUrl:
    Value: !GetAtt Api.Outputs.Url

Resources:

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        JobsTable: !Ref JobsTable
        AuthPublicKey: !Ref AuthPublicKey
        AuthAlgorithm: !Ref AuthAlgorithm
        AuthGroupName: !Ref AuthGroupName
        AuthAppUid: !Ref AuthAppUid
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
      TemplateURL: api/cloudformation.yml

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcId: !Ref VpcId
        EDLUsername: !Ref EDLUsername
        EDLPassword: !Ref EDLPassword
        RtcGammaImage: !Ref RtcGammaImage
        ContentBucket: !Ref ContentBucket
      TemplateURL: batch-cluster/cloudformation.yml

  StepFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        JobQueueArn: !GetAtt Cluster.Outputs.JobQueueArn
        RtcGammaJobDefinition: !GetAtt Cluster.Outputs.RtcGammaJobDefinition
        JobsTable: !Ref JobsTable
        Bucket: !Ref ContentBucket
      TemplateURL: step-function/cloudformation.yml

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True

  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: s3-access-logs/content-bucket/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: False
        RestrictPublicBuckets: False
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: !Ref ProductLifetimeInDays
          - Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${ContentBucket.Arn}/*"

  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_id
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
