name: tests

on: push

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt

    - env:
        JOB_QUEUE: job-queue
        JOB_DEFINITION: job-definition
        AWS_DEFAULT_REGION: us-west-2
        PYTHONPATH: api
      run: pytest api
