openapi: 3.0.1

info:
  title: hyp3-api
  version: ""

security:
  - EarthDataLogin: []

paths:

  /jobs:

    post:
      description: Submits a list of jobs for processing.
      operationId: hyp3_api.handlers.post_jobs
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/post_jobs_body"
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobs_response"

    get:
      description: Get list of previously run jobs.
      operationId: hyp3_api.handlers.get_jobs
      parameters:
        - name: status_code
          in: query
          schema:
            $ref: "#/components/schemas/status_code"
        - name: start
          in: query
          schema:
            $ref: "#/components/schemas/datetime"
        - name: end
          in: query
          schema:
            $ref: "#/components/schemas/datetime"
        - name: name
          in: query
          schema:
            $ref: "#/components/schemas/name"

      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobs_response"
  /user:
    get:
      description: Get information about the logged in user.
      operationId: hyp3_api.handlers.get_user
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"

components:
  schemas:

    post_jobs_body:
      description: List for new jobs to submit for processing.
      type: object
      required:
        - jobs
      additionalProperties: false
      properties:
        validate_only:
          $ref: "#/components/schemas/validate_only"
        jobs:
          $ref: "#/components/schemas/list_of_new_jobs"

    jobs_response:
      description: List of submitted jobs.
      type: object
      required:
        - jobs
      additionalProperties: false
      properties:
        validate_only:
          $ref: "#/components/schemas/validate_only"
        jobs:
          $ref: "#/components/schemas/list_of_jobs"

    user:
      description: Information about a user (quota, user id)
      type: object
      required:
        - user_id
        - quota
      properties:
        user_id:
          $ref: "#/components/schemas/user_id"
        quota:
          $ref: "#/components/schemas/quota"

    quota:
      description: Containes the limit of jobs per month and the amount remaining for a user.
      type: object
      required:
        - limit
        - remaining
      properties:
        limit:
          type: integer
          minimum: 0
        remaining:
          type: integer
          minimum: 0

    list_of_new_jobs:
      description: Contains a list of new job objects.
      type: array
      minItems: 1
      maxItems: 25
      items:
        $ref: "#/components/schemas/new_job"

    new_job:
      description: Contains user provided information on runnning a new job.
      type: object
      required:
        - job_type
        - job_parameters
      additionalProperties: false
      example:
        job_parameters:
          granule: S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8
        job_type: RTC_GAMMA
        name: Job Name

      properties:
        job_type:
          $ref: "#/components/schemas/job_type"
        job_parameters:
          $ref: "#/components/schemas/job_parameters"
        name:
          $ref: "#/components/schemas/name"

    list_of_jobs:
      type: array
      items:
        $ref: "#/components/schemas/job"

    job:
      description: Contains information about a submitted job.
      type: object
      required:
        - job_id
        - user_id
        - job_type
        - job_parameters
        - request_time
        - status_code
      additionalProperties: false
      properties:
        job_id:
          $ref: "#/components/schemas/job_id"
        user_id:
          $ref: "#/components/schemas/user_id"
        job_type:
          $ref: "#/components/schemas/job_type"
        job_parameters:
          $ref: "#/components/schemas/job_parameters"
        request_time:
          $ref: "#/components/schemas/datetime"
        status_code:
          $ref: "#/components/schemas/status_code"
        name:
          $ref: "#/components/schemas/name"
        files:
          $ref: "#/components/schemas/list_of_files"
        browse_images:
          $ref: "#/components/schemas/list_of_urls"
        thumbnail_images:
          $ref: "#/components/schemas/list_of_urls"
        expiration_time:
          $ref: "#/components/schemas/datetime"

    validate_only:
      type: boolean
      default: false

    job_id:
      description: Unique identifier for a job
      type: string
      format: uuid
      example: 27836b79-e5b2-4d8f-932f-659724ea02c3

    user_id:
      description: Username from Earthdata Login.
      type: string
      example: myUserId

    job_type:
      description: Type of process to run this job.
      type: string
      example: RTC_GAMMA
      enum:
        - RTC_GAMMA
# Holding INSAR GAMMA support until Vertex integration is ready
        - INSAR_GAMMA

    job_parameters:
      oneOf:
        - $ref: "#/components/schemas/rtc_gamma_job_parameters"
        - $ref: "#/components/schemas/insar_gamma_job_parameters"

    insar_gamma_job_parameters:
      description: Options and parameters for running the job process.
      type: object
      required:
        - granule1
        - granule2
      additionalProperties: false
      properties:
        granule1:
          $ref: "#/components/schemas/granule_slc"
        granule2:
          $ref: "#/components/schemas/granule_slc"
        include_inc_map:
          $ref: "#/components/schemas/include_inc_map"
        looks:
          $ref: "#/components/schemas/looks"
        include_los_displacement:
          $ref: "#/components/schemas/los_displacement"


    rtc_gamma_job_parameters:
      description: Options and parameters for running the job process.
      type: object
      required:
        - granule
      additionalProperties: false
      properties:
        granule:
          $ref: "#/components/schemas/granule"
        resolution:
          $ref: "#/components/schemas/resolution"
        radiometry:
          $ref: "#/components/schemas/radiometry"
        speckle_filter:
          $ref: "#/components/schemas/speckle_filter"
        scale:
          $ref: "#/components/schemas/scale"
        dem_matching:
          $ref: "#/components/schemas/dem_matching"
        include_dem:
          $ref: "#/components/schemas/include_dem"
        include_inc_map:
          $ref: "#/components/schemas/include_inc_map"

    granule:
      oneOf:
        - $ref: "#/components/schemas/granule_slc"
        - $ref: "#/components/schemas/granule_grdh"

    granule_grdh:
      description: The name of the Sentinel-1 GRDH granule to process.
      type: string
      pattern: "^S1[AB]_IW_GRDH_*"
      minLength: 67
      maxLength: 67
      example: S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8

    granule_slc:
      description: The name of the Sentinel-1 SLC granule to process.
      type: string
      pattern: "^S1[AB]_IW_SLC__*"
      minLength: 67
      maxLength: 67
      example: S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8

    resolution:
      description: Desired output resolution in meters.
      type: number
      enum:
        - 30.0

    radiometry:
      description: Backscatter coefficient normalization, either by ground area (sigma0) or illuminated area projected into the look direction (gamma0)
      type: string
      enum:
        - gamma0
        - sigma0

    scale:
      description: Output image scale
      type: string
      enum:
        - power
        - amplitude

    speckle_filter:
      description: Apply an enhanced lee speckle filter
      default: false
      type: boolean

    dem_matching:
      description: Attempt to match the DEMs otherwise use dead-reckoning
      default: false
      type: boolean

    include_dem:
      description: Include the DEM files in the product package
      default: false
      type: boolean

    include_inc_map:
      description: Include the incident angle map in the product package
      default: false
      type: boolean

    looks:
      description: Number of looks to take in range and azimuth
      type: string
      enum:
        - 20x4
        - 10x2

    los_displacement:
      description: Include a GeoTIFF in the product package containing the displacements along the Line-Of-Sight (LOS)
      default: false
      type: boolean

    datetime:
      description: Date and time object formatted according to ISO 8601
      type: string
      format: date-time
      example: 2020-06-04T18:00:03+00:00

    status_code:
      description: Status of a submitted job.
      type: string
      enum:
        - PENDING
        - RUNNING
        - SUCCEEDED
        - FAILED
      example: SUCCEEDED

    name:
      description: User provided text to name the job
      type: string
      minLength: 1
      maxLength: 20
      example: Job Name

    list_of_files:
      description: List of downloadable files generated by the job.
      type: array
      items:
        type: object
        required:
          - filename
          - size
          - url
        additionalProperties: False
        properties:
          filename:
            type: string
          size:
            type: integer
            minimum: 0
          url:
            type: string

    list_of_urls:
      type: array
      items:
        type: string

  securitySchemes:
    EarthDataLogin:
      description: |-
        Authentication requires the user to have an account at urs.earthdata.nasa.gov and log in at auth.asf.alaska.edu
      type: apiKey
      in: cookie
      name: asf-urs
      x-apikeyInfoFunc: hyp3_api.auth.decode_token
