openapi: 3.0.1

info:
  title: hyp3-api
  version: 0.0.1

security:
  - EarthDataLogin: []

paths:
  /jobs:
    post:
      operationId: hyp3_api.handlers.submit_job
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/submission"
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
    get:
      operationId: hyp3_api.handlers.list_jobs
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobs"

components:
  schemas:

    response:
      type: object
      properties:
        jobId:
          type: string
          format: uuid
      required:
        - jobId
      additionalProperties: false

    submission:
      type: object
      properties:
        job_type:
          $ref: "#/components/schemas/job_type"
        job_parameters:
          $ref: "#/components/schemas/job_parameters"
        description:
          $ref: "#/components/schemas/description"
      required:
        - job_type
        - job_parameters
      additionalProperties: false

    job_parameters:
      type: object
      properties:
        granule:
          type: string
          pattern: "^S1[AB]_IW_SLC__*"
          minLength: 67
          maxLength: 67
          example: S1B_IW_SLC__1SDV_20200604T082207_20200604T082234_021881_029874_5E38
          description: The name of the Sentinel-1 granule to process.  Only SLC products with beam mode IW are supported.
      required:
        - granule
      additionalProperties: false

    job_type:
      type: string
      example: RTC_GAMMA
      enum:
        - RTC_GAMMA

    description:
      type: string
      minLength: 1

    jobs:
      type: array
      items:
        type: object
        required:
          - job_id
          - user_id
          - job_type
          - job_parameters
          - start_time
          - status_code
        additionalProperties: false
        properties:
          job_id:
            type: string
            format: uuid
            example: 27836b79-e5b2-4d8f-932f-659724ea02c3
          user_id:
            type: string
            example: myUserId
          job_type:
            $ref: "#/components/schemas/job_type"
          job_parameters:
            $ref: "#/components/schemas/job_parameters"
          start_time:
            type: string
            format: date-time
            example: 2020-06-04T18:00:03.548Z
          status_code:
            type: string
            enum:
              - RUNNING
              - SUCCEEDED
              - FAILED
            example: SUCCEEDED
          description:
            $ref: "#/components/schemas/description"


  securitySchemes:
    EarthDataLogin:
      description: |-
        Authentication requires the user to have an account at urs.earthdata.nasa.gov and log in at auth.asf.alaska.edu
      type: apiKey
      in: cookie
      name: asf-urs
      x-apikeyInfoFunc: hyp3_api.auth.decode_token
