AWSTemplateFormatVersion: 2010-09-09

Parameters:

  JobQueueArn:
    Type: String

  JobDefinition:
    Type: String

Outputs:

  ApiEndpoint:
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"

Resources:

  SubmitJob:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        JobQueueArn: !Ref JobQueueArn
        JobDefinition: !Ref JobDefinition
      TemplateURL: submit-job/cloudformation.yml

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref AWS::StackName
      Body:
        openapi: 3.0.1
        info:
          title: hyp3-api
          version: 0.0.1
        servers:
          - url: https://yxedp20dk1.execute-api.us-west-2.amazonaws.com/{basePath} #TODO create custom url
            variables:
              basePath:
                default: /v1
        paths:
          /jobs:
            post:
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/submitJob"
                required: true
              responses:
                "200":
                  description: 200 response
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Empty"
              x-amazon-apigateway-request-validator: Validate body
              x-amazon-apigateway-integration:
                type: aws_proxy
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SubmitJob.Outputs.LambdaArn}/invocations"
                httpMethod: POST
                passthroughBehavior: when_no_match
                credentials: !GetAtt IamRole.Arn
                responses:
                  default:
                    statusCode: 200
        components:
          schemas:
            Empty:
              title: Empty Schema
              type: object
            submitJob:
              title: JobInputModel
              required:
                - granule
              type: object
              properties:
                granule:
                  type: string
              additionalProperties: false
        x-amazon-apigateway-request-validators:
          Validate body:
            validateRequestParameters: false
            validateRequestBody: true

  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi

  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: v1
      RestApiId: !Ref RestApi
      DeploymentId: !Ref Deployment

  IamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref AWS::StackName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: apigateway.amazonaws.com
          Effect: Allow
      Policies:
      - PolicyName: policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource: 
            - !GetAtt SubmitJob.Outputs.LambdaArn
