asj-zappa:

  project_name: hyp3

  runtime: python3.8
  app_function: hyp3_api.application
  memory_size: 128
  keep_warm: false

  s3_bucket: ${TEMPLATE_BUCKET}
  aws_environment_variables:
    JOB_QUEUE: ${JOB_QUEUE}
    JOB_DEFINITION: ${JOB_DEFINITION}
    AUTH_ALGORITHM: RS256
    AUTH_PUBLIC_KEY: ${AUTH_PUBLIC_KEY}
  extra_permissions:
    - Effect: Allow
      Action: batch:SubmitJob
      Resource:
        - ${JOB_QUEUE}
        - ${JOB_DEFINITION}
