name: Lint CloudFormation Templates

on: [push, pull_request]

jobs:
  cloudformation-linter:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run cfn-lint
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: **/*.yml
