name: Deploy to AWS

on:
  push:
    branches: 
    - master
    - develop

env:
  AWS_REGION: us-west-2
  TEMPLATE_BUCKET: cf-templates-aubvn3i9olmk-us-west-2
  RTC_GAMMA_IMAGE: 845172464411.dkr.ecr.us-west-2.amazonaws.com/rtc-gamma:develop

  VPC_ID: ${{ secrets.VPC_ID }}
  EDL_USERNAME: ${{ secrets.EDL_USERNAME }}
  EDL_PASSWORD: ${{ secrets.EDL_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to AWS CloudFormation
      run: |
        aws cloudformation package \
          --template-file cloudformation.yml \
          --s3-bucket ${{ env.TEMPLATE_BUCKET }} \
          --output-template-file packaged.yml
        aws cloudformation deploy \
          --stack-name hyp3-${GITHUB_REF##*/} \
          --template-file packaged.yml \
          --role-arn ${{ env.CLOUDFORMATION_ROLE_ARN }} \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
              VpcId=${{ env.VPC_ID }} \
              EDLUsername=${{ env.EDL_USERNAME }} \
              EDLPassword=${{ env.EDL_PASSWORD }} \
              RtcGammaImage=${{ env.RTC_GAMMA_IMAGE }}
