name: Static code analysis

on: push

jobs:

  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          pip install flake8  flake8-import-order flake8-blind-except flake8-builtins

      - run: flake8 --max-line-length=120 --import-order-style=pycharm --statistics --application-import-names hyp3_api,get_files,start_execution,update_db,upload_log,dynamo,process_new_granules

  cfn-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          pip install -r requirements-all.txt
          python apps/render_cf.py --job-types-file job_types.yml

      - uses: scottbrenner/cfn-lint-action@v2
        with:
          args: "--ignore-checks W3002 --template **/*cf.yml"

  openapi-spec-validator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-all.txt
          python -m pip install openapi-spec-validator click prance
          python apps/render_cf.py --job-types-file job_types.yml

      - run: prance validate --backend=openapi-spec-validator apps/api/src/hyp3_api/api-spec/openapi-spec.yml


  statelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install statelint
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          pip install -r requirements-all.txt
          python apps/render_cf.py --job-types-file job_types.yml

      - run: |
          sed -i 's/"Resource": "${.*}"/"Resource": "foo:bar"/' apps/step-function.json
          statelint apps/step-function.json
