name: Static code analysis

on: push

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          make install

      - run: make flake8

  cfn-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        security_environment: [ASF, EDC, JPL]
        instance_types: ['r5d.xlarge', 'r5d.xlarge c5d.large']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          make install

      - run: |
          make security_environment=${{ matrix.security_environment }} instance_types='${{ matrix.instance_types }}' cfn-lint

  openapi-spec-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          make install

      - run: make openapi-validate

  statelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install statelint
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          make install

      - run: |
          make render
          sed -i 's/"Resource": "${.*}"/"Resource": "foo:bar"/' apps/step-function.json
          statelint apps/step-function.json

  call-secrets-analysis-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@main
