name: Static code analysis

on: push

jobs:

  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
      - run: make flake8

  cfn-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          pip install --upgrade pip
          make install
          make render

      - uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint --info --ignore-checks W3002 --template **/*cf.yml

  openapi-spec-validator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-all.txt

      - run: make openapi-validate


  statelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install statelint
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          pip install -r requirements-all.txt
          make render

      - run: |
          sed -i 's/"Resource": "${.*}"/"Resource": "foo:bar"/' apps/step-function.json
          statelint apps/step-function.json
