name: Run tests

on: push

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: pytest api
        env:
          PYTHONPATH: api/src
        run: |
          export $(xargs < api/tests/cfg.env)
          pytest api

      - name: pyest get_files
        env:
          PYTHONPATH: step-function/get-files
        run: pytest step-function/get-files
