name: Run tests

on: push

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements-all.txt

      - name: pytest apps
        env:
          PYTHONPATH: apps/api/src:apps/get-files/src:apps/start-execution/src
        run: |
          export $(xargs < tests/api/cfg.env)
          pytest tests
